# Generated by Django 6.0 on 2025-12-19 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 26, 20, 35, 10, 745109, tzinfo=datetime.timezone.utc)),
        ),
    ]
