# Generated by Django 6.0 on 2025-12-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_role_approved',
            field=models.BooleanField(default=False),
        ),
    ]
