# Generated by Django 6.0 on 2025-12-16 21:46

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_teammember_is_role_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2025, 12, 23, 21, 46, 5, 486087, tzinfo=datetime.timezone.utc))),
                ('is_used', models.BooleanField(default=False)),
                ('suggested_role', models.CharField(choices=[('assistant', 'Assistant Coach'), ('player', 'Player')], default='player', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
