# Generated by Django 5.2.9 on 2026-02-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessedWebhookEvent',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
