# Generated by Django 6.0 on 2025-12-21 21:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_created_at_teammember_joined_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'member')},
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', through='account.TeamMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
