# Generated by Django 6.0 on 2025-12-19 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_invitationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 26, 20, 50, 52, 638200, tzinfo=datetime.timezone.utc)),
        ),
    ]
