# Generated by Django 5.2.9 on 2025-12-20 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_invitationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 27, 17, 57, 40, 656257, tzinfo=datetime.timezone.utc)),
        ),
    ]
