# Generated by Django 6.0 on 2025-12-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_teammember_unique_together_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='team_profiles/'),
        ),
    ]
