# Generated by Django 6.0 on 2025-12-16 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_invitationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 23, 22, 1, 53, 291845, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('assistant', 'Assistant Coach'), ('player', 'Player')], default='player', max_length=20),
        ),
    ]
