# Generated by Django 5.2.9 on 2026-02-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('join_request', 'Join Request'), ('request_accepted', 'Request Accepted'), ('team_message', 'Team Message'), ('assignment', 'New Assignment'), ('reminder', 'Practice Reminder')], max_length=30),
        ),
    ]
