# Generated by Django 6.0 on 2025-12-22 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_team_team_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='teams', through='teamapp.TeamMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
