# Generated by Django 6.0 on 2025-12-16 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_invitationtoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 23, 22, 1, 56, 800546, tzinfo=datetime.timezone.utc)),
        ),
    ]
