# Generated by Django 6.0 on 2025-12-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='Team_Category',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
