# Generated by Django 5.2.9 on 2025-12-23 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_team_team_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', through='account.TeamMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
