# Generated by Django 5.2.9 on 2026-01-02 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_team_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitationtoken',
            options={},
        ),
        migrations.RemoveField(
            model_name='invitationtoken',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='invitationtoken',
            name='suggested_role',
        ),
        migrations.AddField(
            model_name='invitationtoken',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_tokens', to='teamapp.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitationtoken',
            name='token',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
