# Generated by Django 5.2.9 on 2026-01-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_invitationtoken_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitationtoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='invitationtoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
