# Generated by Django 5.2.9 on 2026-01-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_invitationtoken_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='Team_Category',
        ),
    ]
