# Generated by Django 5.2.9 on 2026-01-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
