# Generated by Django 5.2.9 on 2025-12-20 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_invitationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 27, 19, 6, 47, 62662, tzinfo=datetime.timezone.utc)),
        ),
    ]
