# Generated by Django 5.2.9 on 2026-01-11 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_processedwebhookevent_subscription_canceled_at_and_more'),
        ('chat_system', '0002_alter_teamchatmessage_team'),
        ('plan', '0006_alter_drill_assign_team'),
        ('teamapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AlterField(
            model_name='notification',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamapp.team'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='member',
        ),
        migrations.DeleteModel(
            name='InvitationToken',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
