# Generated by Django 5.2.9 on 2026-01-18 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_team_coach_remove_team_members_and_more'),
        ('chat_system', '0002_alter_teamchatmessage_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='related_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chat_system.teamchatmessage'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('join_request', 'Join Request'), ('team_message', 'Team Message')], max_length=30),
        ),
    ]
