# Generated by Django 6.0 on 2025-12-20 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_invitationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 27, 23, 46, 44, 575140, tzinfo=datetime.timezone.utc)),
        ),
    ]
