# Generated by Django 5.2.9 on 2025-12-21 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_alter_invitationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 28, 0, 30, 33, 958284, tzinfo=datetime.timezone.utc)),
        ),
    ]
