# Generated by Django 5.2.9 on 2025-12-21 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_alter_invitationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 28, 1, 49, 21, 78966, tzinfo=datetime.timezone.utc)),
        ),
    ]
