# Generated by Django 5.2.9 on 2025-12-21 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_alter_invitationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 28, 17, 56, 5, 325184, tzinfo=datetime.timezone.utc)),
        ),
    ]
