# Generated by Django 5.2.9 on 2026-02-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_drills',
            field=models.IntegerField(default=5, help_text='5 for free, -1 for unlimited'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_practice_plans',
            field=models.IntegerField(default=5, help_text='5 for free, -1 for unlimited'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('Free / limited access plan', 'free'), ('Single Team paid Plan', 'Pro'), ('Multiple Teams paid Plan / Club Discount', 'Elite')], max_length=50),
        ),
    ]
