# Generated by Django 5.2.9 on 2026-02-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscriptionplan_max_drills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('free', 'Free Mode'), ('Pro', 'Pro Plan'), ('Elite', 'Elite Plan')], max_length=50),
        ),
    ]
