# Generated by Django 5.2.9 on 2026-01-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='team_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
