# Generated by Django 5.2.9 on 2026-03-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='team_position',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
