# Generated by Django 5.2.9 on 2026-01-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0002_teammember_team_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='team_position',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
