# Generated by Django 5.2.9 on 2026-01-18 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
