# Generated by Django 5.2.9 on 2025-12-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
