# Generated by Django 5.2.9 on 2025-12-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_faq_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='privacy_policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
