# Generated by Django 5.2.9 on 2025-12-21 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_aboutus_termsandconditions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='privacy_policy',
            options={'verbose_name': 'Privacy Policy', 'verbose_name_plural': 'Privacy Policy'},
        ),
        migrations.AlterModelOptions(
            name='termsandconditions',
            options={'verbose_name': 'Terms and Conditions', 'verbose_name_plural': 'Terms and Conditions'},
        ),
    ]
