"""
Django settings for water_break project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

# ========== 1. BASE_DIR ডিফাইন করুন ==========
BASE_DIR = Path(__file__).resolve().parent.parent

# ========== 2. .env ফাইল লোড করুন ==========
env_path = BASE_DIR / '.env'
load_dotenv(dotenv_path=env_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-rng7naf36fbtet009!*bz4%8ed1lj46!j(xw)dhf1o^4zv$!v&'
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '*',
    '74.208.158.27',
    'localhost',
    '127.0.0.1',
    '10.10.10.46',
]

AUTH_USER_MODEL = 'account.User'

# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third party apps
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',


    # Local apps
    'account',
    'plan',
    'chat_system',
    'subscription',
    'service',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'water_break.urls'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",
}


# ==================== JWT ====================

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=20),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'water_break.wsgi.application'


"""======================Admin deshboard design UNFOLD settings======================"""


UNFOLD = {
    "SITE_HEADER": "Water Break Admin",
    "SITE_TITLE": "Water Break",
    "SITE_SYMBOL": "admin_panel_settings",
    "SHOW_ALL_APPLICATIONS": False,
    "DENSE": False,
    "COLORS": {
        "primary": {
            "50": "236 254 255", "100": "207 250 254", "200": "165 243 252",
            "300": "103 232 249", "400": "34 211 238", "500": "6 182 212",
            "600": "8 145 178", "700": "14 116 144", "800": "21 94 117", "900": "22 78 99",
        },
    },
    "USER_AVATAR": "avatar",
    "USER_STR_FUNC": "get_full_name", 

    # "SIDEBAR": {
    #     "show_search": True,
    #     "navigation": [
    #         {
    #             "title": "USER MANAGEMENT",
    #             "separator": True,
    #             "items": [
    #                 {
    #                     "title": "Users",
    #                     "link": "/admin/account/user/", 
    #                     "icon": "manage_accounts",
    #                 },
    #                 {
    #                     "title": "Profiles",
    #                     "link": "/admin/account/profile/",
    #                     "icon": "person", 
    #                 },
    #                 {
    #                     "title": "Invitation tokens",
    #                     "link": "/admin/account/invitationtoken/", 
    #                     "icon": "vpn_key",
    #                 },
    #                 {
    #                     "title": "Subscriptions",
    #                     "link": "/admin/account/subscription/", 
    #                     "icon": "card_membership",
    #                 },
    #                 {
    #                     "title": "Team members",
    #                     "link": "/admin/account/teammember/", 
    #                     "icon": "groups",
    #                 },
    #             ],
    #         },
    #         {
    #             "title": "PRACTICE PLAN",
    #             "separator": True,
    #             "items": [
    #                 {
    #                     "title": "Plans",
    #                     "link": "/admin/plan/plan/",
    #                     "icon": "format_list_bulleted", 
    #                 },
    #                 {
    #                     "title": "Drills",
    #                     "link": "/admin/plan/drill/",
    #                     "icon": "category", 
    #                 },
    #                 {
    #                     "title": "Blocks",
    #                     "link": "/admin/plan/block/",
    #                     "icon": "grid_view",
    #                 },
    #             ],
    #         },
    #         {
    #             "title": "SERVICE & CONTENT",
    #             "separator": True,
    #             "items": [
    #                 {
    #                     "title": "About Us",
    #                     "link": "/admin/service/aboutus/",
    #                     "icon": "info",
    #                 },
    #                 {
    #                     "title": "FAQs",
    #                     "link": "/admin/service/faq/",
    #                     "icon": "quiz",
    #                 },
    #                 {
    #                     "title": "Terms & Conditions",
    #                     "link": "/admin/service/termsandconditions/",
    #                     "icon": "gavel",
    #                 },
    #                 {
    #                     "title": "Privacy Policy",
    #                     "link": "/admin/service/privacy_policy/",
    #                     "icon": "policy",
    #                 },
    #             ],
    #         },
    #     ],
    # },
}



# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES= {
    'default': {
        'ENGINE': os.getenv('ENGINE'),
        'NAME': os.getenv('NAME'),
        'USER': os.getenv('USER'),
        'PASSWORD': os.getenv('PASSWORD'),
        'HOST': os.getenv('HOST'),
        'PORT': os.getenv('PORT')
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS= [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE= 'en-us'

TIME_ZONE= 'UTC'

USE_I18N= True

USE_TZ= True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL= '/static/'
# STATICFILES_DIRS = [
#     BASE_DIR / "static",
# ]
STATIC_ROOT= BASE_DIR / 'staticfiles'
MEDIA_URL= '/media/'
MEDIA_ROOT= os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD= os.getenv('DEFAULT_AUTO_FIELD')


EMAIL_BACKEND= os.getenv('EMAIL_BACKEND')
EMAIL_HOST= os.getenv('EMAIL_HOST')
EMAIL_USE_TLS= os.getenv('EMAIL_USE_TLS') == 'True'
EMAIL_PORT= os.getenv('EMAIL_PORT')
EMAIL_HOST_USER= os.getenv('EMAIL_HOST_USER')

EMAIL_HOST_PASSWORD= os.getenv('EMAIL_HOST_PASSWORD')


GOOGLE_OAUTH2_CLIENT_ID= os.getenv('GOOGLE_OAUTH2_CLIENT_ID')
GOOGLE_OAUTH2_CLIENT_SECRET= os.getenv('GOOGLE_OAUTH2_CLIENT_SECRET')
GOOGLE_OAUTH2_REDIRECT_URI= os.getenv('GOOGLE_OAUTH2_REDIRECT_URI')
