# Generated by Django 5.2.9 on 2026-01-11 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0001_initial'),
        ('teamapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamchatmessage',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='teamapp.team'),
        ),
    ]
