# Generated by Django 6.0 on 2025-12-19 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_invitationtoken_expires_at'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prectice_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.drill')),
                ('assign_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.teammember')),
            ],
        ),
    ]
