# Generated by Django 6.0 on 2025-12-22 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_team_team_profile_pic'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='assign_team',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='teamapp.team'),
            preserve_default=False,
        ),
    ]
