# Generated by Django 5.2.9 on 2026-02-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='assign_team_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
