# Generated by Django 5.2.9 on 2026-01-30 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='assigned_members',
            field=models.ManyToManyField(blank=True, help_text='Sub-team members who can VIEW this drill', related_name='assigned_drills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drill',
            name='assistant_coach',
            field=models.ForeignKey(blank=True, help_text='Assistant coach who can MANAGE this drill', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_drills', to=settings.AUTH_USER_MODEL),
        ),
    ]
