# Generated by Django 6.0 on 2025-12-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_drill_create_by_drill_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='description',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
