# Generated by Django 6.0 on 2025-12-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='assign_team',
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
