# Generated by Django 6.0 on 2025-12-22 00:14

import django.db.models.deletion
from django.db import migrations, models


def remove_duplicate_blocks(apps, schema_editor):
    Block = apps.get_model('plan', 'Block')
    # Keep the first block per drill_id, delete the rest
    seen = set()
    for b in Block.objects.all().order_by('id'):
        drill_id = getattr(b, 'drill_id', None)
        if drill_id is None:
            continue
        if drill_id in seen:
            b.delete()
        else:
            seen.add(drill_id)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('account', '0004_team_team_profile_pic'),
        ('plan', '0002_alter_drill_assign_team'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_blocks, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='block',
            name='drill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plan.drill'),
        ),
        migrations.RemoveField(
            model_name='drill',
            name='assign_team',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='Plan_Block',
        ),
        migrations.AddField(
            model_name='drill',
            name='assign_team',
            field=models.ManyToManyField(to='teamapp.team'),
        ),
        migrations.AddField(
            model_name='plan',
            name='Plan_Block',
            field=models.ManyToManyField(to='plan.block'),
        ),
    ]
