# Generated by Django 5.2.9 on 2026-02-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_block_create_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
