# Generated by Django 6.0 on 2025-12-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_alter_block_drill_remove_drill_assign_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='block',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
