# Generated by Django 6.0 on 2025-12-22 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_alter_block_end_time_alter_block_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='drill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.drill'),
        ),
    ]
