# Generated by Django 5.2.9 on 2026-01-11 20:01

from django.db import migrations, models


def copy_account_teams_to_teamapp(apps, schema_editor):
    # Copy existing Team rows from the old account.Team model into teamapp.Team
    try:
        AccountTeam = apps.get_model('account', 'Team')
    except LookupError:
        return

    TeamAppTeam = apps.get_model('teamapp', 'Team')
    # Copy all teams preserving primary keys so existing M2M rows remain valid
    for old in AccountTeam.objects.all():
        TeamAppTeam.objects.update_or_create(
            id=old.id,
            defaults={
                'name': old.name,
                'team_profile_pic': getattr(old, 'team_profile_pic', None),
                'coach_id': getattr(old, 'coach_id', None),
                'created_at': getattr(old, 'created_at', None),
                'updated_at': getattr(old, 'updated_at', None),
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_alter_block_drill'),
        ('teamapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_account_teams_to_teamapp, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='drill',
            name='assign_team',
            field=models.ManyToManyField(to='teamapp.team'),
        ),
    ]
