# Generated by Django 5.2.9 on 2026-01-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_notification_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='prectice_time',
        ),
        migrations.AddField(
            model_name='plan',
            name='end_prectice_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='start_prectice_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
