# Generated by Django 5.2.9 on 2026-01-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_remove_plan_prectice_time_plan_end_prectice_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='color_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
