# Generated by Django 5.2.9 on 2026-01-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_block_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='Plan_Block',
            field=models.ManyToManyField(blank=True, null=True, to='plan.block'),
        ),
    ]
