# Generated by Django 5.2.9 on 2026-01-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_alter_plan_plan_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='Plan_Block',
            field=models.ManyToManyField(blank=True, to='plan.block'),
        ),
    ]
