# Generated by Django 5.2.9 on 2026-01-21 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0012_plan_create_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='Plan_Block',
        ),
        migrations.AddField(
            model_name='block',
            name='prectice_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Plan_Block', to='plan.plan'),
        ),
    ]
