# Generated by Django 5.2.9 on 2026-01-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0013_remove_plan_plan_block_block_prectice_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='prectice_plan',
            new_name='practice_plan',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='end_prectice_time',
            new_name='end_practice_time',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='start_prectice_time',
            new_name='start_practice_time',
        ),
    ]
