# Generated by Django 5.2.9 on 2026-01-23 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0014_rename_prectice_plan_block_practice_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='drill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='plan.drill'),
        ),
    ]
