# Generated by Django 5.2.9 on 2026-01-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0015_alter_block_drill'),
        ('teamapp', '0003_alter_teammember_team_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='assign_team',
            field=models.ManyToManyField(blank=True, related_name='drills', to='teamapp.team'),
        ),
    ]
